name: AllAPILoader
main: georgianYT\AllAPILoader\Main
version: 1.0.5
api: [2.0.0, 3.0.0, 3.0.5, 3.0.4, 3.0.0, 3.0.1, 3.0.2, 4.0.0]
author: georgianYT
description: Makes the server load every plugin regardless of the API version
website: https://github.com/georgianYT/AllAPILoader
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
